### ISSUE TITLE
admin-bar.php is in different directory than ....

### ISSUE THREAD

**Issue by pkpatricia** [KnowTheCode/UpDevTools#10]
this file is located someplace else:

[9:02] 
dhcp25:config patriciaparker$ pwd
/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/config
dhcp25:config patriciaparker$ ls
admin-bar.php
dhcp25:config patriciaparker$

[9:03] 
this is the error i get:

[9:03] 
Whoops\Exception\ErrorException thrown with message “include(/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/assets/css/admin-bar.php): failed to open stream: No such file or directory”

Re-ran composer installl and got:
dhcp25:UpDevTools patriciaparker$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
dhcp25:UpDevTools patriciaparker$

**Comment by pkpatricia** [comment]
so I changed the file but still get:
Whoops \ Exception \ ErrorException (E_WARNING)
include(/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/assets/config/admin-bar.php): failed to open stream: No such file or directory

**Comment by hellofromtonya** [comment]
For the admin bar, you have 2 files:

1. config file which is located in [`config/admin-bar.php`](https://github.com/KnowTheCode/UpDevTools/blob/master/config/admin-bar.php)

2. A CSS file which is located in [`assets/css/admin-bar.php`](https://github.com/KnowTheCode/UpDevTools/blob/master/assets/css/admin-bar.php)

Here's the error you are getting:

include(/Users/patriciaparker/Documents/Websites/genesis.dev/wp-content/plugins/UpDevTools/assets/css/admin-bar.php)

That's telling you that PHP was told to load `assets/css/admin-bar.php`, but it couldn't find that file.  Why? Because I failed to push it to the repository.  You posted the issue just before it was pushed.

The file is there now, [which you can view here](https://github.com/KnowTheCode/UpDevTools/blob/master/assets/css/admin-bar.php).  Go ahead and grab that file.  Everything will work for you now.
